schema: "classroom50/repo-config/v1"
classroom: "indprog"
assignment: "02-conveyor-belt"
owner:
  username: "frederikussing"
  id: 234558121
  accepted_at: "2026-09-13T19:01:00Z"
source:
  owner: "indprog"
  owner_id: 316953525
  repo: "python-template"
  branch: "main"
